project_name: "RAG_Benchmark"

dataset_name: "Qasper"

adapter:
  module: "src.adapters.qasper_adapter"
  class_name: "QasperAdapter"

store:
  type: "lightrag"
  lightrag_config_path: "lightrag.conf"

execution:
  max_workers: 10
  ingest_workers: 4
  retrieval_topk: 5
  max_queries: null
  skip_ingestion: false

paths:
  raw_data: "Data/{dataset_name}/qasper-dev-v0.3.json"
  doc_output_dir: "Data/{dataset_name}/per_query/lightrag/processed_docs"
  vector_store: "Data/{dataset_name}/per_query/lightrag/store_index"
  output_dir: "Output/{dataset_name}/per_question_lightrag"
  log_file: "Output/{dataset_name}/per_question_lightrag/benchmark.log"

llm:
  model: "doubao-seed-1-8-251228"
  temperature: 0
  base_url: "https://ark.cn-beijing.volces.com/api/v3"
  api_key: "269f7ee6-212a-4f46-9472-978a55cdb625"
