project_name: "RAG_Benchmark"

dataset_name: "HotpotQA"

adapter:
  module: "src.adapters.hotpotqa_adapter"
  class_name: "HotpotQAAdapter"

execution:
  max_workers: 16
  ingest_workers: 16
  retrieval_topk: 5
  max_queries: 30
  skip_ingestion: false

paths:
  raw_data: "ruc-ov-eval/Data/{dataset_name}/hotpot_dev_test30.json"
  doc_output_dir: "ruc-ov-eval/Data/{dataset_name}/processed_docs"
  vector_store: "ruc-ov-eval/Data/{dataset_name}/viking_store_index"
  output_dir: "ruc-ov-eval/Output/{dataset_name}/experiment_test30"
  log_file: "ruc-ov-eval/Output/{dataset_name}/experiment_test30/benchmark.log"

llm:
  model: "doubao-seed-1-8-251228"
  temperature: 0
  base_url: "https://ark.cn-beijing.volces.com/api/v3"
  api_key: "76aab4eb-95e0-453e-b898-7934260ae6a1"
