project_name: "RAG_Benchmark"

# ===========修改配置================
dataset_name: "SyllabusQA_test" 

adapter:
  module: "src.adapters.syllabusqa_adapter"  
  class_name: "SyllabusQAAdapter"     

execution:
  max_workers: 5
  ingest_workers: 5
  retrieval_topk: 5
  max_queries: 10
  skip_ingestion: false
# ==================================  

paths:
  raw_data: "Data/SyllabusQA/test.csv"
  doc_output_dir: "Data/SyllabusQA_test/processed_docs"
  vector_store: "Data/SyllabusQA_test/viking_store_index"
  output_dir: "Output/SyllabusQA_test/experiment_1"
  log_file: "Output/SyllabusQA_test/experiment_1/benchmark.log"


llm:
  model: "doubao-seed-1-8-251228"
  temperature: 0
  base_url: "https://ark.cn-beijing.volces.com/api/v3"
  api_key: "76aab4eb-95e0-453e-b898-7934260ae6a1"
