project_name: "RAG_Benchmark"

dataset_name: "ClapNQ"

adapter:
  module: "bench_framework.adapters.clapnq_adapter"
  class_name: "ClapNQAdapter"

vector_store:
  module: "bench_framework.stores.pageindex_store"
  class_name: "PageIndexStoreWrapper"

execution:
  max_workers: 1
  ingest_workers: 1
  retrieval_topk: 5
  max_queries: null
  skip_ingestion: false

paths:
  raw_data: "Data/clapnq-main"
  doc_output_dir: "Data/clapnq-main/processed_docs"
  vector_store: "Data/clapnq-main/pageindex_store"
  output_dir: "Output/ClapNQ/pageindex_exp"
  log_file: "Output/ClapNQ/pageindex_exp/benchmark.log"

llm:
  model: "doubao-seed-2-0-pro-260215"
  temperature: 0
  base_url: "https://ark.cn-beijing.volces.com/api/v3"
  api_key_env_var: "LLM_API_KEY"
  api_key: "269f7ee6-212a-4f46-9472-978a55cdb625"
